### ISSUE TITLE
cgi deprecation

### ISSUE THREAD

**Issue by rafalkrupinski** [falconry/python-mimeparse#48]
Hi guys,
python 3.13 is in beta now. Any chance to release a version with the dependency on `cgi` removed?

**Comment by vytas7** [comment]
Yes, we'll try to get out a new version before 3.13 is released.

**Comment by CaselIT** [comment]
is the plan to vendor the functions from the cgi module used like it was done in falcon?

**Comment by vytas7** [comment]
Hi @gorilla-seb, yes, we'll try to get out a release shortly.

Falcon had some checks in the CI to verify that we were vendoring the latest version, I will need to temporarily (or permanently if we decide to reimplement what we need) disable these checks for the impending release of this project.

**Comment by rafalkrupinski** [comment]
My tests pass with the RC.

I only use `best_match`

**Comment by vytas7** [comment]
Thanks for checking, @rafalkrupinski!
I have now cut a stable release, [`python-mimeparse` v2.0](https://github.com/falconry/python-mimeparse/releases/tag/2.0.0), so you can update your dependencies.

**Comment by gorilla-seb** [comment]
Looks to be working fine, many thanks @vytas7!
